### ISSUE TITLE
BTML .net version issues

### ISSUE THREAD

**Issue by m22spencer** [janxious/BattleTechModLoader#13]
Someone earlier was having .net issues with BTML/RTML.

I had them test my profiler which is also 3.5 and uses Mono.Cecil to do injection on the main BattleTech assembly, and it works no problem.  (It uses only assemblies from the Managed folder)

RTML is pulling in System.IO.Compression.FileSystem and System.IO.Compression from the GAC, which seems like it might be causing the issue.

The working csproj in question is here https://gist.github.com/m22spencer/1ebc163328a38f364da74dbecf391d66

If that file were to be made crossplatform (mac/windows specific search paths & post-build events), and restricted to only these specific dependencies, RTML should work without issue.
The Compression dependency can be removed by distributing the factions as a single json file.

Your thoughts?

**Comment by janxious** [comment]
I agree it was an issue. I already tried removing it here: https://github.com/janxious/BattleTechModLoader/compare/master...janxious:what-if-three-five#diff-118b2d99360dfd1dbf403e8014740be8.

Am I missing something?

**Comment by m22spencer** [comment]
Can you send me the dll built from your machine? I want to see what it tries to load.

**Comment by m22spencer** [comment]
I found your test build on roguetech crew: "Anyone with issues with .NET issues on win 10 please replace the injector bundled with RT with this and tell us if it works for you."

Tested this build, and it also pulls in System.IO.Compression, and System.IO.Compression.FileSystem from the GAC.  It references them directly.

**Comment by m22spencer** [comment]
https://github.com/janxious/BattleTechModLoader/releases/tag/v0.7.0

The 3.5 release pulls `Mono.Cecil`, but it's not distributed with BTML/RTML. If you include that, I think everything should be good to go.

**Comment by m22spencer** [comment]
Oh, and `0harmony` as noted by kato42  in this other issue: https://github.com/janxious/BattleTechModLoader/issues/15

**Comment by janxious** [comment]
Mono.Cecil *shouldn't* be  necessary, given the fody stuff, but also I blasted the config for that so maybe it didn't get recreated properly.
