### ISSUE TITLE
BTML v0.7

### ISSUE THREAD

**Issue by kato42** [janxious/BattleTechModLoader#15]
I downloaded the BTML v0.7 as v0.64 and 0.63 didn't work for me.  Unfortunately neither does this one.

I noted that it was said this was for .NET 3.5, my windows install says it has 3.5.1, and my software installation list has 4.5, 4.5.1, and 4.6.2.  I'm still running Win 7, mostly because I detest rebuilding my computer.  Besides, the machine is a few years old anyway.

When I try to run it from Windows, in the same folder as the 2 .dll files, it closes immediately.
Does this version not use 0Harmony.dll?  It wasn't in the zip.  I used an older version.

Here is the error BTML throws when I try to run it by command line:

ERROR: An exception occured: System.IO.FileLoadException: Could not load file or
 assembly 'Mono.Cecil, Version=0.10.1.0, Culture=neutral, PublicKeyToken=50cebf1
cceb9d05e' or one of its dependencies. Method does not exist. (Exception from HR
ESULT: 0x80131513)
File name: 'Mono.Cecil, Version=0.10.1.0, Culture=neutral, PublicKeyToken=50cebf
1cceb9d05e' ---> System.MissingMethodException: Method not found: 'Void System.T
hreading.Monitor.Enter(System.Object, Boolean ByRef)'.
   at Costura.AssemblyLoader.ResolveAssembly(Object sender, ResolveEventArgs e)
   at System.AppDomain.OnAssemblyResolveEvent(String assemblyFullName)
   at BattleTechModLoader.BTMLInjector.IsInjected(String dllPath, Boolean& isCur
rentInjection, String& gameVersion)
   at BattleTechModLoader.BTMLInjector.Main(String[] args)

If I am doing something wrong, or there is some small thing I can install that would fix this, let me know.
Thanks.

**Comment by kato42** [comment]
Adding the mono.cecil.dll to the managed folder seems to have made all the difference. BTML installed properly, and mods seem to be working fine.

Wonder if it would help with the 0.6.4 version too?

**Comment by janxious** [comment]
No, Mono.Cecil.dll is just for the 0.7.0 version.
