### ISSUE TITLE
fails to inject MOD loader

### ISSUE THREAD

**Issue by Darkhorse069** [janxious/BattleTechModLoader#17]
Dear Sir
After the recent update from STEAM, the MOD loader is failing to re inject itself.
Usually a small screen comes up and asks you to go ahead, at this time it flashes on for a second and then disappears...have I done something wrong or is it just the latest update that has stuffed things up?
Anyway thanks for the injector, it has made a good game GREAT!
Cheers
Troy

**Comment by CptMoore** [comment]
Wrong project, see https://github.com/BattletechModders/ModTek for a pre-release version
